### ISSUE TITLE
US/NA version?

### ISSUE THREAD

**Issue by livxy** [leo-avitabile/autotrader-car-data-viewer#1]
Would it be possible to have a United States version of the application? The url would just be https://www.autotrader.com/

**Comment by leo-avitabile** [comment]
Hello,

Thank you for your interest!

Unfortunately, clause 6.D.3 of the [Visitor Agreement](https://www.autotrader.com/legal/visitor-agreement) explicitly forbids "systematic extraction of data or data fields ... by use of any automated mechanism, such web robots, crawlers, or spiders".

So, for now at least, even if the tool was updated to support the site, it would be against the sites TOS to use it. 

Good luck in your search!

Regards,

Leo

**Comment by livxy** [comment]
Thank you so much for your quick comment on this! I appreciate you taking the time to answer! :)
